### PR TITLE
fix: detect already running instance of IPFS

### LINKED ISSUE #28: If an IPFS node already runs then Aragon Desktop fails to start
This is actually from me force-quitting Aragon Desktop, which (I suppose) left the IPFS daemon hanging around.

If you run Aragon Desktop while an IPFS node is already running on port :5001, then the app fails to start.

```
> aragon-desktop@1.0.0 start /Users/onbjerg/Workspace/aragon/aragon-desktop
> electron .

Initializing daemon...
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/darwin
Golang version: go1.11.1
Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)

Error: no IPFS repo found in /Users/onbjerg/.ipfs.
please run: 'ipfs init'

ipfs exited with code: 1, signal: null
initializing IPFS node at /Users/onbjerg/.ipfs
generating 2048-bit RSA keypair...done
peer identity: QmQW5miE6vUfeBFzDdjYCXimxuMC9ti8wjXVKcmNP8haAj
to get started, enter:

	ipfs cat /ipfs/QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv/readme


Initializing daemon...
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/darwin
Golang version: go1.11.1

2019-01-22 09:02:31.432 Electron[52548:13885095] *** WARNING: Textured window <EventDispatchingWindow: 0x7fc23c63d430> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.94.0.1/tcp/4001
Swarm listening on /ip4/127.94.0.2/tcp/4001
Swarm listening on /ip4/192.168.1.149/tcp/4001
Swarm listening on /ip4/192.168.99.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit

Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.94.0.1/tcp/4001
Swarm announcing /ip4/127.94.0.2/tcp/4001
Swarm announcing /ip4/152.115.88.30/tcp/38733
Swarm announcing /ip4/192.168.1.149/tcp/4001
Swarm announcing /ip4/192.168.99.1/tcp/4001
Swarm announcing /ip6/::1/tcp/4001

Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use
```

### PR DESCRIPTION
**Pull request by sohkai**
Fixes #28 

A bit hacky, but seems to work ok 👌. Accessing the IPFS api (e.g. pinning) seems to work with a pre-existing daemon as long as the daemon's running on the default port.

cc @onbjerg

### CODE REVIEW

File: src/main.js [hunk 1]
```diff
@@ -20,8 +21,14 @@ async function loadAragonClient (network = 'main') {
...
-  // Start IPFS first so we can pin it afterwards
-  await ipfsInstance.start()
+  try {
+    const version = await ipfsInstance.api.ipfsApi.version()
+    console.log('Detected running instance of IPFS, no need to start our own')
+  } catch (e) {
+    console.log('Could not detect running instance of IPFS, starting it ourselves...')
+    await ipfsInstance.start()
+    startedIpfs = true
+  }
```
Comment (onbjerg) [inline src/main.js]: what about

```js
await ipfsInstance.api.ipfsApi.version()
  .catch(() => {
    startedIpfs = true
    return ipfsInstance.start()
  })
```

**Comment by onbjerg** [comment]
github needs a 👌 react

File: src/main.js (hunk 1 above)
Comment (sohkai) [reply src/main.js]: Hmm, I think the `try / catch` is more obvious as an either/or situation.
